- name: install nginx server
  apt:
    name:
      - nginx
    state: latest
- name: upload website to nginx
  copy:
    src: html
    dest: /var/www
    owner: root
    group: root
    mode: 0777
- name: remove default nginx config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
- name: configure nginx for 1st site
  copy:
    src: nginx/default
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: 0622
  notify: restart_nginx
- name: configure nginx for 2nd site
  copy:
    src: nginx/mysite
    dest: /etc/nginx/sites-available
    owner: root
    group: root
    mode: 0622
  notify: restart_nginx
- name: create symlink for 1st site
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    owner: root
    group: root
    state: link
  notify: restart_nginx
- name: create symlink for 2nd site
  file:
    src: /etc/nginx/sites-available/mysite
    dest: /etc/nginx/sites-enabled/mysite
    owner: root
    group: root
    state: link
  notify: restart_nginx
- name: check if nodejs is installed
  stat:
    path: /usr/local/lib/nodejs
  register: nodejs
- name: install tar
  apt:
    name: tar
- name: install nodejs
  unarchive:
    src: https://nodejs.org/dist/v18.12.1/node-v18.12.1-linux-x64.tar.xz
    dest: /usr/local/lib
    remote_src: yes
    owner: root
    group: root
    mode: 0755
  when: nodejs.stat.exists == false
- name: Check if file exists
  stat:
    path: /usr/local/lib/node-v18.12.1-linux-x64
  register: old_nodejs_folder
- name: rename extracted folder to nodejs
  shell:
    cmd: mv node-v18.12.1-linux-x64/ nodejs
    chdir: /usr/local/lib/
  when: old_nodejs_folder.stat.exists
- name: remove old folder
  file:
    path: /usr/local/lib/node-v18.12.1-linux-x64
    state: absent
  when: old_nodejs_folder.stat.exists
- name: save nodejs PATH
  blockinfile:
    path: /home/hazard/.profile
    marker: "# {mark} Nodejs PATH"
    block: "export PATH=/usr/local/lib/nodejs/bin:$PATH"
    backup: yes
  notify: source_dot_profile
- name: verify nodejs installation
  shell: . ~/.profile && node -v
  register: node_version
- name: print nodejs version
  debug:
    msg: "{{ node_version.stdout }}"
