---

- hosts: server_2
  become: true
  tasks:
    - name: install tar
      apt:
        name: tar
    - name: install nodejs
      unarchive:
        src: https://nodejs.org/dist/v18.12.1/node-v18.12.1-linux-x64.tar.xz
        dest: /usr/local/lib
        remote_src: yes
    - name: rename extracted folder to nodejs
      copy: 
        src: /usr/local/lib/node-v18.12.1-linux-x64
        dest: /usr/local/lib/nodejs
        remote_src: yes
    - name: remove old folder
      file:
        path: /usr/local/lib/node-v18.12.1-linux-x64
        state: absent
