---

- hosts: all
  become: true
  pre_tasks:
    - name: update repo index
      apt:
        update_cache: yes
      changed_when: false

- hosts:  all
  become: true
  roles:
    - base

- hosts: server_1
  become: true
  roles:
    - server_1

- hosts: server_2
  become: true
  roles:
    - server_2
